development:
  adapter: postgresql
  database: COOKUP_DEV
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: COOKUP_TEST
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: COOKUP_PROD
  pool: 5
  timeout: 5000
