# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2595a8c683a3d7d34c2bc8e1dfdcaedadadf43259ae3a01276e35ea1f56822b9c72ccf6bd5202c6990a0a1c08fb8f5a657d6de40699588085241d2713ce02856

test:
  secret_key_base: 06da87ad1dd49c56b96ad3bbb3b53412833c98cfffac4ce628ca05d0ff6168d05e22caf9efaf2971da740bb40e35b496fd04bc34ecc3a077b8871ab0a7b9e6b4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
